### ISSUE TITLE
Checking and unchecking "Labels" checkbox

### ISSUE THREAD

**Issue by GrimMaple** [denis-adamchuk/mrHelper#106]
Checking and unchecking the "Labels" checkbox should filter out merge request without having to press apply. The same goes for entering text I think.

**Comment by denis-adamchuk** [comment]
As to checkbox - sounds reasonable, thank you (I dislike Apply button personally), but as to "enter text"... the app should be smart enough to apply changed text not on any keystroke but somehow else... Needs some investigation of best practices in user experience.

**Comment by GrimMaple** [comment]
I think that a reasonable solution would be to parse the text after a space key is pressed and see if labels had changed - then apply filters if necessary.

**Comment by GrimMaple** [comment]
After a space key is pressed or the control loses focus - that would be even better
