### ISSUE TITLE
Allowing to select the same commit [discuss]

### ISSUE THREAD

**Issue by GrimMaple** [denis-adamchuk/mrHelper#19]
I have checked the behaviour of GitLab UI and it **allows** selecting same commit for both left and right. Should we allow to do that too?

**Comment by denis-adamchuk** [comment]
It seems to be a bug in GitLab :) When I select a commit at the left side and then select the same commit at the right side it thinks for a moment and then selected _previous_ commit at the right side.
Does it work the same way with your merge requests?

**Comment by GrimMaple** [comment]
Somehow I am able to select same commits and the UI just displays "No files found"

**Comment by denis-adamchuk** [comment]
I cannot reproduce it again, but anyway I don't think it is useful to allow this. Do you?

**Comment by GrimMaple** [comment]
Yea, I totally agree that it's useless to allow such a thing. I think we should automatically adjust the commits when they are being selected.

**Comment by denis-adamchuk** [comment]
Why checkComboboxVersionsOrder() is not enough?
