### ISSUE TITLE
Show number of unresolved discussions in the list of MRs

### ISSUE THREAD

**Issue by denis-adamchuk** [denis-adamchuk/mrHelper#222]

**Comment by Radrik5** [comment]
Consider adding total number of discussions as well, just for reference.
For example, unresolved discussions: "3 / 5".

**Comment by denis-adamchuk** [comment]
> Consider adding total number of discussions as well, just for reference.
> For example, unresolved discussions: "3 / 5".
> Or resolved threads: "2 / 5" (as in GitLab).

Sure :)
