### ISSUE TITLE
mrHelper won't connect to GitLab after VPN connected. 

### ISSUE THREAD

**Issue by ak0nst** [denis-adamchuk/mrHelper#389]
STR: run mrH with the host behind the VPN before VPN connected. 
Workaround: restart the application

**Comment by denis-adamchuk** [comment]
Thank you for reporting this one!
Yep, connectivity issues are not handled properly now and this is one of areas for improvements.
So far you have a work-around, "Workflow" tab -> "Select Host" -> Re-select a host in a drop-down list, and the app reconnects
