### ISSUE TITLE
Show commit message near to commit has tag

### ISSUE THREAD

**Issue by denis-adamchuk** [denis-adamchuk/mrHelper#4]
Not sure if it should be a tooltip or inside a dropdown

**Comment by GrimMaple** [comment]
Is this issue still relevant? I think it can be closed.

**Comment by denis-adamchuk** [comment]
I would keep it because it is not done yet :) What is done is only commit title. Full message is not shown.
Application UI is being refactored these days so I think we will be able to show a selected commit message on the screen too.

**Comment by denis-adamchuk** [comment]
Closed for now. To be reopened later if someone advises where it is better to show this information.
"Near to hash tag" does not make sense.

**Comment by denis-adamchuk** [comment]
Finally implemented in 719958b01c3fb81c437aad0de81db79b85b94d3e
