### ISSUE TITLE
Submodule causing issues

### ISSUE THREAD

**Issue by GrimMaple** [denis-adamchuk/mrHelper#50]
The GtiLabSharp submodule is causing issues when cloning. It uses ssh and if the local computer doesn't have ssh configured it will be impossible to clone the repo. It is better to update the submodule to use https instead.

**Comment by denis-adamchuk** [comment]
Well... What's the difference between cloning it using SSH from git@github.com:denis-adamchuk/GitLabSharp.git? If it neither work, may be it is a user-side issue?
Anyway, I don't have enough experience with submodules. If they are *normally* configured to HTTPs, let's do this. Do you know how to do it? :)
