### ISSUE TITLE
Form scaling

### ISSUE THREAD

**Issue by GrimMaple** [denis-adamchuk/mrHelper#7]
It is possible to scale the form right now, which leads to improper results. Either border-fixing, either form contents scaling is required.
![img](https://user-images.githubusercontent.com/10130860/60340454-44444a80-99b4-11e9-8400-c9ee6596df09.png)

**Comment by denis-adamchuk** [comment]
Yep, it was a sad bug, but I fixed it in #e38049dc1aa3a85dba83120cb5eae97d098d295d. Thank you!
